server:
  port: 1202
spring:
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/christmas
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100


mybatis:
  mapper-locations: classpath:mappers/*.xml